### ISSUE TITLE
typo in Makefile

### ISSUE THREAD

**Issue by mcshane** [thegenemyers/MERQURY.FK#1]
`libfastK.h` should be `libfastk.h` in the Makefile here: 

https://github.com/thegenemyers/MERQURY.FK/blob/f8f9f0c490aab128f7a3c0847efc38bdafe13a86/Makefile#L9

**Comment by thegenemyers** [comment]
Thanks.  Fixed & committed.  Gene

**Comment by mcshane** [comment]
Thanks Gene.
