### ISSUE TITLE
Small bugs in Smudges

### ISSUE THREAD

**Issue by c-zhou** [thegenemyers/MERQURY.FK#2]
Hello Gene,

There are a few small bugs in the Smudges.

* `SRC` would not be the right path if the ktab file is in a different directory
https://github.com/thegenemyers/MERQURY.FK/blob/bbf1a1a1a882ea47ad45b1f9b607e22a1b54ebd3/Smudges.c#L1724

* `f` could be NULL here
https://github.com/thegenemyers/MERQURY.FK/blob/bbf1a1a1a882ea47ad45b1f9b607e22a1b54ebd3/Smudges.c#L1753

* `tname[100]` could be too short to store the ktab file path (`SRC`), e.g., ktab file is in a different directory
https://github.com/thegenemyers/MERQURY.FK/blob/bbf1a1a1a882ea47ad45b1f9b607e22a1b54ebd3/Smudges.c#L1762

Chenxi

**Comment by thegenemyers** [comment]
Chenxi,

    Thanks for the bug report.  I addressed them all and checked a 
revision in to the github repo.

    I reworked IO so that SRC is now just argv[1] (which would correctly 
in include any path) and OUT
is the root name of argv[1] (without any path) and is used as the plot title

    The issue with tname was also true for several command buffers where 
I was lazy and just
used a number i thought big enough.  I addressed all of these.

    I did not test the changes thoroughly, they were all "mechanical".  
Please let me know if any
problems remain or somehow I didn't get it 100% right.

     Thanks again,
         Gene
