### ISSUE TITLE
CNspectra README

### ISSUE THREAD

**Issue by mcshane** [thegenemyers/MERQURY.FK#3]
Hi Gene,

In the README for `CNspectra` should
```<asm>.<read>.prof produced by FastK -p: -k<K> [...] <assembly> -N<asm>```
be
```<asm>.<read>.prof produced by FastK -p:<read> -k<K> [...] <assembly> -N<asm>.<read>```
??

**Comment by iggyB** [comment]
Hej,

README is almost correct. The last part is still missing:
`<asm>.<read>.prof produced by FastK -p:<read> -k<K> [...] <assembly> -N<asm>`
should be
`<asm>.<read>.prof produced by FastK -p:<read> -k<K> [...] <assembly> -N<asm>.<read>`

Cheers,
Iggy
