### ISSUE TITLE
mismatch between header and data for completeness.stats ouput

### ISSUE THREAD

**Issue by mcshane** [thegenemyers/MERQURY.FK#7]
Hi Gene,

The header line for the `completeness.stats` output has just two columns, but the data output has five columns.

https://github.com/thegenemyers/MERQURY.FK/blob/fd00feae44bcd09704c374c2c76fae8e5c7b978e/MerquryFK.c#L898

e.g.

```
Assembly        % Covered
icNebBrev1.p_ctg        all     164792625       189666036       86.89
icNebBrev1.a_ctg        all     155142808       189666036       81.80
both    all     184229239       189666036       97.13
```

**Comment by thegenemyers** [comment]
OK, should be fixed now, 5 column headers.  -- Gene

**Comment by mcshane** [comment]
Thanks Gene.
