### ISSUE TITLE
SORT_PATH typo

### ISSUE THREAD

**Issue by mcshane** [thegenemyers/MERQURY.FK#8]
This should be `/tmp` rather than `\tmp`:

https://github.com/thegenemyers/MERQURY.FK/blob/12bab0bd9c622a15e3f832e9c551c86f723a1372/MerquryFK.c#L585

**Comment by thegenemyers** [comment]
Yes, I've made the same mistake before, sorry.  Its fixed at github now.
Thanks,
   -- Gene
